## server
server:
  port: 80 #端口号
spring:
## datasource
  datasource:
    dbtype: mysql
    name: dataSource #数据库名称
    type: com.alibaba.druid.pool.DruidDataSource
#基本属性
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.95.124.75:3306/admin?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: Pa55w0rd#75
#druid相关配置
    druid:
#监控统计拦截的filters
      filters: stat
#配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
#获取连接等待超时时间
      max-wait: 60000
#间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
#一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
#打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
## redis
  redis:
    database: 0
    host: localhost
    port: 16379
    password: 1234
    timeout: 1000
    jedis:
      pool:
        max-idle: 200
        max-wait: -1
        min-idle: 0
## 登录设置
auth:
  excludeUrls:
  - /user/login
  - /index